# Login and Team Information
# Can be found here: https://github.com/cwendt94/espn-api/discussions/150
# Set SWID and ESPN_S2 to None if you don't have them,
# but program will be restricted to public leagues
SWID: "your_swid"
ESPN_S2: "your_espn_s2"

# Your league and team name
# Can be found here:
LEAGUE_ID: "your_league_id"
Team Name: "your_team_name"

# The highest number of players allowed per team in your league
Maximum Team Size: 16

# Whether or not to check free agents
Check Free Agents: True

# Considers trades with up to X players
Maximum Trade Size: 3

# Other team managers are unlikely to accept trades which are not in their favor
# This is the maximum trade edge, in percent, that will be considered
Maximum Trade Edge: 0.005

# % Of value benched players have on the opponent's team when considering
# trades with them. Too high and trades will favor bench improvements over
# actual team improvements, which isn't mutual. Too low and you will devalue
# players off their bench.
Opponent Bench Weight: 0.2

# Development Settings
# Proxies currently don't work
Use Proxies: False
User Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
